name: PR Comment

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get list of changed files
        id: changed-files
        uses: actions/github-script@v6
        with:
          script: |
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const fileList = files.map(file => `- ${file.filename}`).join('\n');
            core.setOutput('files', fileList);

      - name: Comment on the pull request
        uses: actions/github-script@v6
        with:
          script: |
            const files = `${{ steps.changed-files.outputs.files }}`;
            const commentBody = `The following files have been changed:\n${files}`;
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody
            });
