name: PR Comment

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get list of changed files
        id: files
        run: |
          files=$(jq -r '.pull_request.filenames | join("\n")' "$GITHUB_EVENT_PATH")
          echo "::set-output name=files::$files"

      - name: Comment on the pull request
        uses: actions/github-script@v6
        with:
          script: |
            const files = `${{ steps.files.outputs.files }}`;
            const lines = files.split("\n").map(file => `- ${file}`).join("\n");
            const commentBody = `The following files have been changed:\n${lines}`;
            github.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: commentBody
            });
